export const ROUTER = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  PROFILE: '/profile',
  FAVORITES: '/product-favorites',
  ABOUT: '/about',
  CONTACT: '/contact',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  FAQ: '/faq',
  NOT_FOUND: '/404',
  COLLECTIONS: '/collections',
  PAYMENT_CALLBACK: '/payment/callback',
  VOUCHERS: '/vouchers',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
} as const;
